services:
  agent:
    env_file: [.env]
    command: sh -c 'bin/wait && python -m deeppavlov_agent.run'
    build:
      context: ./
      dockerfile: dockerfile_agent
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  mongo:
    command: mongod
    image: mongo:4.0.0
    ports:
      - $DB_PORT:$DB_PORT

  rabbitmq:
    image: rabbitmq:management
    env_file: ".env"
    hostname: $AMQP_HOST
    environment:
      - RABBITMQ_NODE_PORT=$AMQP_PORT
      - RABBITMQ_DEFAULT_USER=$AMQP_USER
      - RABBITMQ_DEFAULT_PASS=$AMQP_PASSWORD
    ports:
      - 15672:15672              # web ui
      - $AMQP_PORT:$AMQP_PORT    # debug

  gateway:
    env_file: ".env"
    build: ./gateway
    # otherwise we would need to solve
    # starting order and non-trivial waiting
    restart: unless-stopped

version: '3.7'
